### ISSUE TITLE
Improve the readability of file names

### ISSUE THREAD

**Issue by citnfm** [robertdebock/ansible-role-autofs#3]
## Proposed feature

Improve the readability of file names by allowing the replacement character for slashes to be set from a variable.

## Rationale

Currently, any slash within the `mountpoint` is removed when creating the file names. When its a nested directory (e.g. `/bind/mount`) the file name for the mount point and path configuration files come out like the following:
```
/etc/auto.master.d/00-bindmount.autofs
/etc/auto.bindmount
```

This approach does not provide an easily readable file name when referencing them in the future. 

Of course, this is a preference, so I am suggesting that the character that replaces the slash in file names be driven by a variable (specifically `slash_replace_char`). 

This will allow the current functionality to remain the same by setting the variable default to `slash_replace_char: ""` but allow others to override it with their preference. For example `slash_replace_char: "-"`, which would produce the following result:
```
/etc/auto.master.d/00-bind-mount.autofs
/etc/auto.bind-mount
```

## Additional context

I will be creating a pull request with my approach on how to handle this within the role.

**Comment by citnfm** [comment]
I found an issue with the recent code updates from pull request #4; A `regex_replace` filter was missed in the `templates/template.autofs.j2` file. This breaks the functionality of the role because the autofs configuration will be pointing to the incorrect file name. I am working on the updates to resolve the issue and improve the molecule testing. I will submit a new pull request once it's ready.

**Comment by robertdebock** [comment]
Release in version 1.2.8. Thanks!
